### ISSUE TITLE
Table column header is not updated

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#142]
-Open test-lingvodoc 
-create your own dictionary (or use existing)
/dictionary/2929/12/perspective/2929/16/publish 
Result: column View published (0)    - OK
![image](https://user-images.githubusercontent.com/59951991/72709784-acd45e00-3b76-11ea-9451-169f56c1e337.png)

- select all checkboxes (or you can use Publish Entries button)
-Click on View published (0) header
Result: all entities are published - OK
Expected: Table column shows  View published (2)
Actual: however, table column is not refreshed View published (0)  
![image](https://user-images.githubusercontent.com/59951991/72710164-8531c580-3b77-11ea-9563-3d04e1e681d2.png)

Workaround: Refresh is needed to see correct values.

**Comment by al-indigo** [comment]
It's needed to refetch counters on publish action

**Comment by jandrew44** [comment]
'qcounter' query is used to obtain counters.
And there is a problem with this query on the backend side.
Looks like it returns some cached value.
At least publish and unpublish operations does not affect it.
@IgorBMSTU FYI.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Covered in tests\test_publish.py

**Comment by nadezhday** [comment]
The problem is not fixed.
http://83.149.198.62/dictionary/4702/70/perspective/4702/71/publish

1) Initial Published
![image](https://user-images.githubusercontent.com/59951991/160755364-a3be33d9-2a0c-43f8-b50f-efa1e97fb489.png)

View Published
![image](https://user-images.githubusercontent.com/59951991/160755424-25cd3523-eb81-4171-8594-2f69c157924d.png)
 
2) Unselect option in Publish
![image](https://user-images.githubusercontent.com/59951991/160755507-67adfaf4-275e-41ec-948f-d2fa2508945a.png)

Problem: View Published in not updated with new info

However word are not iin the View published table

![image](https://user-images.githubusercontent.com/59951991/160755633-fca43c86-2316-4e47-a251-5268d2bc8175.png)
