### ISSUE TITLE
Problems with select user field in Role dialog

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#207]
1) Login as admin.
2) Open /dictionary/482/4/perspective/482/5/view
3) Open Lexical Entries>Roles...
![image](https://user-images.githubusercontent.com/59951991/77750620-27b56b80-7035-11ea-89d0-3ea20a4e58b6.png)
Result: Select user field is empty. - OK
4) Click Remove user
![image](https://user-images.githubusercontent.com/59951991/77751035-fc7f4c00-7035-11ea-9647-360537e83838.png)

Expected: text 'select user' should be present in select user field. 
Actual: After removing user from Role dialog name of deleted user can be found in select user field. - NOK

Scenario 2:
5)Click on select user field.
Why do we have "Пчелинцев" automatically selected?
![image](https://user-images.githubusercontent.com/59951991/77751325-8d562780-7036-11ea-86e6-82b8a5eaac7f.png)
6) click somewhere else 
Expected: Select user field should stay empty
Actual:  "Пчелинцев" is selected.
![image](https://user-images.githubusercontent.com/59951991/77751467-d60de080-7036-11ea-8b37-3567f89a32c3.png)

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verification.
We still have problems with select user field, problems are reported in https://github.com/ispras/lingvodoc-react/issues/210 Select user field in the Role dialog.

**Comment by vmonakhov** [comment]
Covered in tests/test_view_lexical_roles.py
