### ISSUE TITLE
Perspective properties: has linked field error

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#254]
Open http://83.149.198.62/dictionary/2815/29/perspective/2815/32/view signed in as administrator, open perspective properties, add 'Sound' and 'Markup' fields, try to link 'Markup' field to the 'Sound' field:
![image](https://user-images.githubusercontent.com/2802467/85930098-417b7e80-b8c2-11ea-83bb-2a61ff5bbe46.png)
![image](https://user-images.githubusercontent.com/2802467/85930102-45a79c00-b8c2-11ea-8475-a7e8c7fcd088.png)
![image](https://user-images.githubusercontent.com/2802467/85930106-4809f600-b8c2-11ea-8b82-f091b7bad498.png)
![image](https://user-images.githubusercontent.com/2802467/85930109-4a6c5000-b8c2-11ea-9450-af9240692394.png)
![image](https://user-images.githubusercontent.com/2802467/85930113-4c361380-b8c2-11ea-8b74-3fc009e5d9e0.png)
![image](https://user-images.githubusercontent.com/2802467/85930119-4e986d80-b8c2-11ea-8d69-a37429d6c89b.png)
![image](https://user-images.githubusercontent.com/2802467/85930123-50fac780-b8c2-11ea-9a4b-f59d49ea95c8.png)

**Comment by myrix** [comment]
Fixed, works ok:
![image](https://user-images.githubusercontent.com/2802467/85930568-404c5080-b8c6-11ea-8ee5-84eb643344df.png)

**Comment by pavel-ho** [comment]
At the moment, the problem is still being reproduced.

How to reproduce:
log in as an administrator
go to http://83.149.198.62/dictionary/2815/29/perspective/2815/32/view

1)
-> lexical entries -> lexical entries properties
Add new column -> Sound
Add new column -> Markup
near the Sound field to tick the "has linked field" and choose Markup.

Delete these two fields
Close the window by pressing the Close button or Esc key

2) the same thing again
open lexical entries again -> lexical entries properties
Add new column -> Sound
Add new column -> Markup
near the Sound field to tick the "has linked field" and choose Markup.

Problems:
-  there is now not one Markup in the list, but two
 
![254-2](https://user-images.githubusercontent.com/67796013/89335446-afc11700-d6a0-11ea-87fa-5d3051b0fe68.png)

- when iterating over them, an error occurs:
![254-4](https://user-images.githubusercontent.com/67796013/89335876-48579700-d6a1-11ea-96c7-d1c3f3c21ab1.png)

**Comment by pavel-ho** [comment]
Covered in Selenium tests.
Test is being skipped now.

**Comment by myrix** [comment]
Fixed, now there are no longer a spurious field in the list of possible linked fields, and there are no errors when changing linked field selection.
