### ISSUE TITLE
Login: Top menu is not updated:  Exception

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#646]
Test tests\test_view_lexical_03.py -  FAILed

Steps to reproduce:

Login as Julia
Logout

Find  Dictionary of Forest dialect of Enets language (1970) 
Click  view(2) and select Lexical Entries
![изображение](https://user-images.githubusercontent.com/59951991/158552070-ecb6d830-98a9-45ad-bece-20072906e5c0.png)

Try to login as admin

![изображение](https://user-images.githubusercontent.com/59951991/158552517-7c02ce74-7827-4f11-94aa-f18228de45e7.png)

Expected: You can see администратор on top menu
Actual:  Instead of адинистратор we can see Sign in menu
![изображение](https://user-images.githubusercontent.com/59951991/158552769-1d4194f9-eac7-412f-ad2f-9a7ae323c840.png)

Workaround: Click f5 to see the correct logged in admin
![изображение](https://user-images.githubusercontent.com/59951991/158553051-68de280f-2a66-4521-8d36-0d0d292f5cf0.png)

Exception

uncaught at c at c 
 at r 
 at r 
 e@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:541496
t.prototype.fetchQuery/M<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1378998
promise callback*t.prototype.fetchQuery@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1378795
e.prototype.refetch@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:531388
t.prototype.getObservableQueryPromises/_<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1386452
t.prototype.getObservableQueryPromises@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1386305
t.prototype.reFetchObservableQueries@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1384165
t.prototype.reFetchObservableQueries@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1372507
T@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721748
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720821
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
T@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721844
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720821
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
promise callback*x@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721210
T@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721805
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720821
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
P@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:723494
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720943
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
s/M/<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721667
r@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717076
s@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717227
i@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717125
M@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721554
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720749
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
promise callback*x@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721210
T@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721805
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720821
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
s@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:725330
A@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:722171
b@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720868
p@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:719688
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:720296
o@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:721400
e@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:447889
a/o<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:448819
o/e</</<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:449102
r@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717076
s@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717227
i@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:717125
o/e</<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:449083
e@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:447476
i/t/</<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1316182
r/</</<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1315634
r/<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1304805
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:766087
r@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1524240
n@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:766121
r/<@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:766659
e/e.handleClick@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1682697
Q@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1181727
tt@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1181811
et@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1181868
fe@http://83.149.198.62/assets/vendor.6ae7b2a5.js:1:1193652
[raven.js:55:31](https://cdn.ravenjs.com/3.18.1/raven.js)
    2]</d/a[b raven.js:55
    Redux 61
    Lodash 4
    handleClick DropdownItem.js:50
    React 4

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
It looks like that the problem is not fixed.
Login does not work.

![image](https://user-images.githubusercontent.com/59951991/158742157-660ef586-ed28-4a4c-9add-973421ca8032.png)

Progress...

**Comment by nadezhday** [comment]
uncaught at l at l 
 at r 
 at r 
 Error: Network error: Store reset while query was in flight(not completed in link chain)
    at new e (http://83.149.198.62/assets/vendor.2800155c.js:1:534873)
    at http://83.149.198.62/assets/vendor.2800155c.js:1:1383409
    at async Promise.all (index 1)
a.<computed> @ raven.js:55
u @ utils.js:225
$ @ proc.js:210
y @ proc.js:349
r @ proc.js:79
t.cont @ proc.js:92
y @ proc.js:356
r @ proc.js:79
t.cont @ proc.js:92
y @ proc.js:356
r @ proc.js:79
t.cont @ proc.js:92
p @ proc.js:328
n @ proc.js:388
(anonymous) @ proc.js:451

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
The problem with login can be reproduced

New scenario:

Tools - Map search (http://83.149.198.62/map_search)
sign in as admin
sign out
Problem: Empty screen

TypeError: l is undefined
    l index.js:129
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    Redux 8
    n createTransitionManager.js:54
    notifyListeners createTransitionManager.js:73
    notifyListeners createTransitionManager.js:72
    k createBrowserHistory.js:95
    P createBrowserHistory.js:186
    n createTransitionManager.js:44
    P createBrowserHistory.js:166
    Redux 43
    Lodash 4
    handleClick DropdownItem.js:50
    React 4


uncaught at l at l 
 at r 
 at i 
 l@http://83.149.198.62/assets/client.620c8cc3.js:1:506080
Dn@http://83.149.198.62/assets/vendor.21c9e902.js:1:1220980
cr@http://83.149.198.62/assets/vendor.21c9e902.js:1:1227818
Xl@http://83.149.198.62/assets/vendor.21c9e902.js:1:1289482
ui@http://83.149.198.62/assets/vendor.21c9e902.js:1:1255302
si@http://83.149.198.62/assets/vendor.21c9e902.js:1:1255230
oi@http://83.149.198.62/assets/vendor.21c9e902.js:1:1255091
$r@http://83.149.198.62/assets/vendor.21c9e902.js:1:1251954
Ze/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1207636
e.unstable_runWithPriority@http://83.149.198.62/assets/vendor.21c9e902.js:1:1299032
We@http://83.149.198.62/assets/vendor.21c9e902.js:1:1207414
Ze@http://83.149.198.62/assets/vendor.21c9e902.js:1:1207584
Ke@http://83.149.198.62/assets/vendor.21c9e902.js:1:1207517
Wr@http://83.149.198.62/assets/vendor.21c9e902.js:1:1249534
enqueueSetState@http://83.149.198.62/assets/vendor.21c9e902.js:1:1282166
a.prototype.setState@http://83.149.198.62/assets/vendor.21c9e902.js:1:1174063
u/</c.prototype.onStateChange@http://83.149.198.62/assets/vendor.21c9e902.js:1:686189
notify@http://83.149.198.62/assets/vendor.21c9e902.js:1:1303749
t.prototype.notifyNestedSubs@http://83.149.198.62/assets/vendor.21c9e902.js:1:1304277
u/</c.prototype.onStateChange@http://83.149.198.62/assets/vendor.21c9e902.js:1:686207
c@http://83.149.198.62/assets/vendor.21c9e902.js:1:687895
i/t/</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1321123
r/</</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1320588
e/a.handleLocationChange@http://83.149.198.62/assets/vendor.21c9e902.js:1:1313383
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:514338
a/notifyListeners/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:514562
notifyListeners@http://83.149.198.62/assets/vendor.21c9e902.js:1:514533
k@http://83.149.198.62/assets/vendor.21c9e902.js:1:691457
v/P/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:692422
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:514232
P@http://83.149.198.62/assets/vendor.21c9e902.js:1:692194
r/</</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1320634
T@http://83.149.198.62/assets/vendor.21c9e902.js:1:713815
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:712888
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:712363
promise callback*x@http://83.149.198.62/assets/vendor.21c9e902.js:1:713277
T@http://83.149.198.62/assets/vendor.21c9e902.js:1:713872
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:712888
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:712363
P@http://83.149.198.62/assets/vendor.21c9e902.js:1:715561
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:713010
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:712363
s/M/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:713734
r@http://83.149.198.62/assets/vendor.21c9e902.js:1:709143
s@http://83.149.198.62/assets/vendor.21c9e902.js:1:709294
i@http://83.149.198.62/assets/vendor.21c9e902.js:1:709192
M@http://83.149.198.62/assets/vendor.21c9e902.js:1:713621
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:712816
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:712363
promise callback*x@http://83.149.198.62/assets/vendor.21c9e902.js:1:713277
T@http://83.149.198.62/assets/vendor.21c9e902.js:1:713872
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:712888
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
s@http://83.149.198.62/assets/vendor.21c9e902.js:1:717397
A@http://83.149.198.62/assets/vendor.21c9e902.js:1:714238
b@http://83.149.198.62/assets/vendor.21c9e902.js:1:712935
p@http://83.149.198.62/assets/vendor.21c9e902.js:1:711755
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:712363
o@http://83.149.198.62/assets/vendor.21c9e902.js:1:713467
e@http://83.149.198.62/assets/vendor.21c9e902.js:1:446553
a/o<@http://83.149.198.62/assets/vendor.21c9e902.js:1:447483
o/e</</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:447766
r@http://83.149.198.62/assets/vendor.21c9e902.js:1:709143
s@http://83.149.198.62/assets/vendor.21c9e902.js:1:709294
i@http://83.149.198.62/assets/vendor.21c9e902.js:1:709192
o/e</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:447747
e@http://83.149.198.62/assets/vendor.21c9e902.js:1:446140
i/t/</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1321136
r/</</<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1320588
r/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:1309759
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:768954
r@http://83.149.198.62/assets/vendor.21c9e902.js:1:1549591
n@http://83.149.198.62/assets/vendor.21c9e902.js:1:768988
r/<@http://83.149.198.62/assets/vendor.21c9e902.js:1:769526
e/e.handleClick@http://83.149.198.62/assets/vendor.21c9e902.js:1:1708048
Q@http://83.149.198.62/assets/vendor.21c9e902.js:1:1186681
tt@http://83.149.198.62/assets/vendor.21c9e902.js:1:1186765
et@http://83.149.198.62/assets/vendor.21c9e902.js:1:1186822
fe@http://83.149.198.62/assets/vendor.21c9e902.js:1:1198606

After clicking F5 the page is loaded.

**Comment by jandrew44** [comment]
Fixed this case as well.

**Comment by nadezhday** [comment]
We still have problem with login (tests\test_dictionaries.py - FAILED on Chrome)

Steps to reproduce:
login as Julia
Logout
login as admin



![image](https://user-images.githubusercontent.com/59951991/159246607-de589a70-1b45-4490-afd1-0413476d040d.png)

raven.js:1270          GET http://83.149.198.62/api/user 404 (Not Found)

**Comment by nadezhday** [comment]
Added wait in tests (in login and logout functions)
