### ISSUE TITLE
Allow removal of incomplete tasks

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#652]
When tasks terminate with an error before being 100% complete, it still should be possible to remove them, otherwise they will hang in the task list indefinitely, cluttering it:
![image](https://user-images.githubusercontent.com/2802467/159106507-db577685-9cbd-4db6-833d-4e03280db8c6.png)

Right now remove button is disabled for partially complete tasks, and we can't do that.

**Comment by myrix** [comment]
Fixed, the button is enabled and hanged tasks can be removed.

**Comment by nadezhday** [comment]
The problem is not fixed. 
I cannot clear completed with error task from Task view
![image](https://user-images.githubusercontent.com/59951991/160360577-bbfd8597-e4d1-4d9f-ac56-791b53a8ae9a.png)

**Comment by nadezhday** [comment]
Verified
Tasks completed with error can be removed from Task view

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_reparsing.py
