### ISSUE TITLE
Import starling dictionary: Field type menu is cut off by the screen edge

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#928]
/import_csv > Columns Mapping > Field Type (for the most left column)
!The drop-down menu can be cut off by the screen edge

![2023-01-20_12-59-17](https://user-images.githubusercontent.com/18721530/213685444-08d58895-a74b-4bf3-9f29-33bbcde296fb.png)

**Comment by nataliauvarova** [comment]
Done

**Comment by vmonakhov** [comment]
The issue is still reproduced. Reopen.

![2023-03-13_17-57-38](https://user-images.githubusercontent.com/18721530/224751427-3928f263-1616-451e-83b2-4127016e99fb.png)
![2023-03-13_17-59-21](https://user-images.githubusercontent.com/18721530/224751440-c601b02d-c9f6-41e7-adbd-e9398b3c955a.png)

**Comment by nataliauvarova** [comment]
Fixed
